version: "0.2"
ignorePaths:
  - './Binaries/**'
  - '.idea/**'
  - '.git/**'
  - '*.csproj.user'
  - '**/.vs/**'
  - '**/obj/**'
  - '**/bin/**'
dictionaryDefinitions:
  - name: vhd-attach
    path: .github/config/vhd-attach.dict
    addWords: true
dictionaries:
  - vhd-attach
